<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusBase\Module'                     => __DIR__ . '/src/DkplusBase/Module.php',
    'DkplusBase\View\Helper\FlashMessenger' => __DIR__ . '/src/DkplusBase/View/Helper/FlashMessenger.php',
);