<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusBase\Controller\CrudController'                 => __DIR__ . '/src/DkplusBase/Controller/CrudController.php',
    'DkplusBase\Module'                                    => __DIR__ . '/src/DkplusBase/Module.php',
    'DkplusBase\Service\Crud\BindFormStrategy'             => __DIR__ . '/src/DkplusBase/Service/Crud/BindFormStrategy.php',
    'DkplusBase\Service\Crud\DoctrineMapper'               => __DIR__ . '/src/DkplusBase/Service/Crud/DoctrineMapper.php',
    'DkplusBase\Service\Crud\FactoryFormStrategy'          => __DIR__ . '/src/DkplusBase/Service/Crud/FactoryFormStrategy.php',
    'DkplusBase\Service\Crud\FormStrategyInterface'        => __DIR__ . '/src/DkplusBase/Service/Crud/FormStrategyInterface.php',
    'DkplusBase\Service\Crud\MapperInterface'              => __DIR__ . '/src/DkplusBase/Service/Crud/MapperInterface.php',
    'DkplusBase\Service\Crud\Service'                      => __DIR__ . '/src/DkplusBase/Service/Crud/Service.php',
    'DkplusBase\Service\Crud\ServiceInterface'             => __DIR__ . '/src/DkplusBase/Service/Crud/ServiceInterface.php',
    'DkplusBase\Service\Exception\EntityNotFound'          => __DIR__ . '/src/DkplusBase/Service/Exception/EntityNotFound.php',
    'DkplusBase\Stdlib\Hydrator\HydrationFactoryInterface' => __DIR__ . '/src/DkplusBase/Stdlib/Hydrator/HydrationFactoryInterface.php',
    'DkplusBase\View\Helper\FlashMessenger'                => __DIR__ . '/src/DkplusBase/View/Helper/FlashMessenger.php',
);