<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusBase\Authentication\Storage\Chain'                         => __DIR__ . '/src/DkplusBase/Authentication/Storage/Chain.php',
    'DkplusBase\Module'                                               => __DIR__ . '/src/DkplusBase/Module.php',
    'DkplusBase\Mvc\Controller\Plugin\NotFoundForward'                => __DIR__ . '/src/DkplusBase/Mvc/Controller/Plugin/NotFoundForward.php',
    'DkplusBase\Mvc\Controller\Plugin\Service\NotFoundForwardFactory' => __DIR__ . '/src/DkplusBase/Mvc/Controller/Plugin/Service/NotFoundForwardFactory.php',
    'DkplusBase\Service\Exception\EntityNotFound'                     => __DIR__ . '/src/DkplusBase/Service/Exception/EntityNotFound.php',
    'DkplusBase\Stdlib\Hydrator\HydrationFactoryInterface'            => __DIR__ . '/src/DkplusBase/Stdlib/Hydrator/HydrationFactoryInterface.php',
    'DkplusBase\View\Helper\FlashMessenger'                           => __DIR__ . '/src/DkplusBase/View/Helper/FlashMessenger.php',
    'DkplusBase\View\Helper\Service\FlashMessengerFactory'            => __DIR__ . '/src/DkplusBase/View/Helper/Service/FlashMessengerFactory.php',
);